import { useCallback, useEffect, useState } from 'react'
import { adminFetch } from '../../admin/api'
import { downloadConsoleCSV } from './csv'
import { ErrorBanner } from './ui'
interface Profile { user_id: string; email?: string; commission_percent: number; settle_threshold_usd: number; daily_code_limit: number; code_value_usd: number; grant_days: number; channel: string; status: string }
interface Settlement { id: string; agent_user_id?: string; email?: string; amount_usd: number; method: string; status: string; requested_at: string; review_note: string; payment_reference: string }
interface Flag { id: string; code_id: string; reason: string; blocking?: boolean; dismissed_at: string | null; review_note: string; email?: string; minimum_seconds: number }
interface Code { id: string; code: string; face_value_usd: number; channel: string; expires_at: string; redeemed_at: string | null; voided_at: string | null }
interface Balance { earned_usd: number; eligible_usd: number; reserved_usd: number; paid_usd: number; available_usd: number }
interface Rules { check_email: boolean; check_device: boolean; minimum_usage_seconds: number }
interface AgentPortal { profile: Profile[]; codes: Code[]; settlements: Settlement[]; flags: Flag[]; balance: Balance; summary: { registered: number; first_topup: number; revenue_12_month_usd: number; hours: number }[]; retention: { week: number; eligible: number; retained: number }[] }
const blankProfile: Profile = { user_id: '', commission_percent: 10, settle_threshold_usd: 100, daily_code_limit: 100, code_value_usd: 10, grant_days: 30, channel: '', status: 'active' }
const money = (amount: number) => `$${amount.toFixed(2)}`
const stateLabel: Record<string, string> = { requested: '待审核', approved: '已通过', paid: '已结算', rejected: '已驳回' }
const reasonLabel: Record<string, string> = { self_email: '自身账户或相同邮箱身份', shared_device: '与代理使用相同设备', minimum_usage: '尚未达到最低使用时长' }
export function AgentsPage({ mode, writable = false, canReview = false, canPay = false, canExport = false }: { mode: 'admin' | 'self'; writable?: boolean; canReview?: boolean; canPay?: boolean; canExport?: boolean }) {
 const [profiles, setProfiles] = useState<Profile[]>([]), [draft, setDraft] = useState<Profile>(blankProfile), [settlements, setSettlements] = useState<Settlement[]>([]), [flags, setFlags] = useState<Flag[]>([]), [portal, setPortal] = useState<AgentPortal | null>(null)
 const [rules, setRules] = useState<Rules>({ check_email: true, check_device: true, minimum_usage_seconds: 600 }), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
 const [quantity, setQuantity] = useState(10), [expiry, setExpiry] = useState(() => new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10)), [requestId, setRequestId] = useState(() => crypto.randomUUID()), [settlementRequest, setSettlementRequest] = useState(() => crypto.randomUUID()), [generated, setGenerated] = useState<string[]>([])
 const load = useCallback(async () => {
  try {
   if (mode === 'self') { const value = await adminFetch<AgentPortal>('/api/agent/portal'); setPortal(value); setSettlements(value.settlements); setFlags(value.flags) }
   else { const [agents, requests, fraud] = await Promise.all([adminFetch<{ agents: Profile[] }>('/api/admin/agents'), adminFetch<{ settlements: Settlement[] }>('/api/admin/settlements'), adminFetch<{ rules: Rules[]; flags: Flag[] }>('/api/admin/agent-fraud')]); setProfiles(agents.agents); setSettlements(requests.settlements); setFlags(fraud.flags); if (fraud.rules[0]) setRules(fraud.rules[0]) }
  } catch (e) { setError(e instanceof Error ? e.message : '读取失败') }
 }, [mode])
 useEffect(() => { void load() }, [load])
 async function mutate(path: string, method: string, body: unknown, onSuccess?: (result: unknown) => void) { setBusy(true); setError(''); setNotice(''); try { const result = await adminFetch(path, { method, body: JSON.stringify(body) }); onSuccess?.(result); setNotice('操作已保存'); await load() } catch (e) { setError(e instanceof Error ? e.message : '保存失败') } finally { setBusy(false) } }
 function review(item: Settlement, action: 'approve' | 'reject' | 'pay') {
  const reference = action === 'pay' && item.method === 'cash' ? window.prompt(`确认已向 ${item.email ?? item.agent_user_id} 付款 ${money(item.amount_usd)}。请输入付款凭据编号：`) : ''
  if (reference == null) return
  const note = action === 'reject' ? window.prompt('驳回原因：') : ''
  if (note == null) return
  void mutate(`/api/admin/settlements/${item.id}/${action}`, 'POST', { note, payment_reference: reference })
 }
 return <div className="pa-stack"><ErrorBanner message={error} onClose={() => setError('')} />{notice && <p role="status">{notice}</p>}
 {mode === 'self' && portal && <><section className="pa-card"><h2>我的代理账户</h2>{!portal.profile.length ? <p>尚未配置代理资料，请联系管理员完成额度和分成设置。</p> : <><p>渠道：{portal.profile[0].channel} · 分成 {portal.profile[0].commission_percent}% · {portal.profile[0].status === 'active' ? '正常' : '已暂停'}</p><p>可申请 {money(portal.balance.available_usd)} · 审核中 {money(portal.balance.reserved_usd)} · 已结算 {money(portal.balance.paid_usd)} · 累计分成（扣退款）{money(portal.balance.earned_usd)}</p><p>每笔真实充值冻结当时比例，归因用户注册后的 12 个月内有效。未满足风控条件的分成暂不可结。低于 {money(portal.profile[0].settle_threshold_usd)} 以一年有效的赠送额度结算，达到门槛以现金结算。</p><button className="pa-button pa-button--primary" disabled={busy || portal.balance.available_usd < 0.01 || portal.profile[0].status !== 'active'} onClick={() => { void mutate('/api/agent/settlements', 'POST', { client_request_id: settlementRequest }, () => setSettlementRequest(crypto.randomUUID())) }}>申请结算全部可结金额</button></>}{portal.summary.map((summary, i) => <p key={i}>已领码注册用户 {summary.registered} · 首充 {summary.first_topup} · 归因 12 个月收入 {money(summary.revenue_12_month_usd)} · 累计使用 {summary.hours.toFixed(2)} 小时</p>)}{portal.retention.map(row => <p key={row.week}>第 {row.week} 周留存：{row.retained} / {row.eligible}</p>)}</section>
 {portal.profile.length > 0 && <section className="pa-card"><h2>生成我的一次性兑换码</h2><p>每码 {money(portal.profile[0].code_value_usd)}，兑换后有效 {portal.profile[0].grant_days} 天，每日最多 {portal.profile[0].daily_code_limit} 个。客户价格、赠送额度使用规则及条款与普通客户一致。</p><form className="pa-form-grid" onSubmit={e => { e.preventDefault(); void mutate('/api/agent/codes', 'POST', { client_request_id: requestId, quantity, expires_at: `${expiry}T23:59:59Z` }, result => { setGenerated((result as { codes: string[] }).codes); setRequestId(crypto.randomUUID()) }) }}><label>数量<input type="number" min="1" max="1000" value={quantity} onChange={e => setQuantity(Number(e.target.value))} required /></label><label>兑换截止日（UTC）<input type="date" value={expiry} onChange={e => setExpiry(e.target.value)} required /></label><button className="pa-button pa-button--primary" disabled={busy || portal.profile[0].status !== 'active'}>生成</button></form>{generated.length > 0 && <><textarea aria-label="代理新生成兑换码" readOnly value={generated.join('\n')} /><button className="pa-button" onClick={() => downloadConsoleCSV('my-new-codes.csv', [['兑换码'], ...generated.map(code => [code])])}>下载本批 CSV</button></>}<p>以下显示最近 1000 个码，生成后可立即下载完整当前批次。</p><button className="pa-button" onClick={() => downloadConsoleCSV('my-codes.csv', [['兑换码', '面值 USD', '截止日期', '兑换时间'], ...portal.codes.map(code => [code.code, code.face_value_usd, code.expires_at, code.redeemed_at])])}>下载我的码 CSV</button><div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>兑换码</th><th>面值</th><th>截止日期</th><th>状态</th></tr></thead><tbody>{portal.codes.map(code => <tr key={code.id}><td><code>{code.code}</code></td><td>{money(code.face_value_usd)}</td><td>{code.expires_at.slice(0, 10)}</td><td>{code.redeemed_at ? '已使用' : code.voided_at ? '已作废' : new Date(code.expires_at).getTime() <= Date.now() ? '已过期' : '可兑换'}</td></tr>)}</tbody></table></div></section>}</>}
 {mode === 'admin' && <><section className="pa-card"><h2>代理配置</h2><p>分成比例的修改只影响之后的充值。配置完成后，在角色权限页为账户分配「代理」角色。</p><div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>账户</th><th>渠道</th><th>比例</th><th>现金门槛</th><th>状态</th><th>操作</th></tr></thead><tbody>{profiles.map(profile => <tr key={profile.user_id}><td>{profile.email}</td><td>{profile.channel}</td><td>{profile.commission_percent}%</td><td>{money(profile.settle_threshold_usd)}</td><td>{profile.status}</td><td>{writable && <button className="pa-button" onClick={() => setDraft(profile)}>编辑</button>}</td></tr>)}</tbody></table></div>{writable && <form onSubmit={e => { e.preventDefault(); void mutate('/api/admin/agents', 'PUT', draft) }}><fieldset disabled={busy}><div className="pa-form-grid"><label>用户 ID<input required value={draft.user_id} onChange={e => setDraft({ ...draft, user_id: e.target.value })} /></label><label>来源渠道<input required maxLength={100} value={draft.channel} onChange={e => setDraft({ ...draft, channel: e.target.value })} /></label>{([['commission_percent', '分成百分比', 0, 100], ['settle_threshold_usd', '现金结算门槛 USD', 0, 1000000], ['daily_code_limit', '每日发码限额', 0, 1000], ['code_value_usd', '每码面值 USD', 0.01, 10000], ['grant_days', '兑换后有效天数', 1, 3650]] as const).map(([key, label, min, max]) => <label key={key}>{label}<input type="number" required min={min} max={max} step={key.endsWith('days') || key.endsWith('limit') ? 1 : 0.01} value={draft[key]} onChange={e => setDraft({ ...draft, [key]: Number(e.target.value) })} /></label>)}<label>状态<select value={draft.status} onChange={e => setDraft({ ...draft, status: e.target.value })}><option value="active">正常</option><option value="suspended">暂停发码与结算</option></select></label></div><button className="pa-button pa-button--primary">保存代理配置</button><button className="pa-button" type="button" onClick={() => setDraft(blankProfile)}>新建配置</button></fieldset></form>}</section>
 <section className="pa-card"><h2>代理刷号规则</h2><p>规则在领码时快照，不影响客户权益。最低使用时长达到后自动允许结算；误判可填写理由解除。</p><form className="pa-form-grid" onSubmit={e => { e.preventDefault(); void mutate('/api/admin/agent-fraud', 'PUT', rules) }}><fieldset disabled={!writable || busy}><label><input type="checkbox" checked={rules.check_email} onChange={e => setRules({ ...rules, check_email: e.target.checked })} />检测相同邮箱身份</label><label><input type="checkbox" checked={rules.check_device} onChange={e => setRules({ ...rules, check_device: e.target.checked })} />检测相同设备</label><label>最低转录秒数<input type="number" min="0" max="86400" value={rules.minimum_usage_seconds} onChange={e => setRules({ ...rules, minimum_usage_seconds: Number(e.target.value) })} /></label><button className="pa-button">保存规则</button></fieldset></form></section></>}
 <section className="pa-card"><h2>结算记录</h2>{canExport && <button className="pa-button" onClick={() => downloadConsoleCSV('agent-settlements.csv', [['ID', '账户', '金额 USD', '方式', '状态', '申请时间', '凭据'], ...settlements.map(item => [item.id, item.email, item.amount_usd, item.method, item.status, item.requested_at, item.payment_reference])])}>下载 CSV</button>}<div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>申请时间 / ID</th>{mode === 'admin' && <th>账户</th>}<th>金额</th><th>方式</th><th>状态 / 说明</th><th>操作</th></tr></thead><tbody>{settlements.map(item => <tr key={item.id}><td>{item.requested_at.slice(0, 10)}<small>{item.id}</small></td>{mode === 'admin' && <td>{item.email}</td>}<td>{money(item.amount_usd)}</td><td>{item.method === 'credit' ? '赠送额度' : '现金'}</td><td>{stateLabel[item.status]} {item.review_note} {item.payment_reference}</td><td>{canReview && item.status === 'requested' && <button className="pa-button" disabled={busy} onClick={() => review(item, 'approve')}>审核通过</button>}{canReview && ['requested', 'approved'].includes(item.status) && <button className="pa-button" disabled={busy} onClick={() => review(item, 'reject')}>驳回</button>}{canPay && item.status === 'approved' && <button className="pa-button pa-button--primary" disabled={busy} onClick={() => review(item, 'pay')}>{item.method === 'credit' ? '发放额度' : '登记已付款'}</button>}</td></tr>)}</tbody></table></div></section>
 <section className="pa-card"><h2>分成风控原因</h2><div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>兑换码 ID</th><th>原因</th><th>状态 / 说明</th><th>操作</th></tr></thead><tbody>{flags.map(flag => <tr key={flag.id}><td>{flag.code_id}</td><td>{reasonLabel[flag.reason]}{flag.reason === 'minimum_usage' ? `（${flag.minimum_seconds} 秒）` : ''}</td><td>{flag.dismissed_at ? '已人工解除' : flag.blocking === false ? '已达到条件' : '待满足条件或审核'} {flag.review_note}</td><td>{writable && !flag.dismissed_at && <button className="pa-button" disabled={busy} onClick={() => { const note = window.prompt('请输入解除此标记的依据：'); if (note) void mutate('/api/admin/agent-fraud', 'PUT', { flag_id: flag.id, note }) }}>解除标记</button>}</td></tr>)}</tbody></table></div></section>
 </div>
}
