import { useCallback, useEffect, useState } from 'react'
import { adminFetch } from '../../admin/api'
import { ErrorBanner } from './ui'
interface Role { id: string; key: string; name: string; permissions: string[]; channels: string[]; builtin: boolean }
const emptyRole: Role = { id: '', key: '', name: '', permissions: [], channels: [], builtin: false }
export function RolesPage({ writable }: { writable: boolean }) {
 const [roles, setRoles] = useState<Role[]>([]), [permissions, setPermissions] = useState<string[]>([]), [draft, setDraft] = useState<Role>(emptyRole)
 const [userId, setUserId] = useState(''), [roleId, setRoleId] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
 const load = useCallback(async () => { try { const result = await adminFetch<{ roles: Role[]; permissions: string[] }>('/api/admin/roles'); setRoles(result.roles); setPermissions(result.permissions) } catch (e) { setError(e instanceof Error ? e.message : '读取失败') } }, [])
 useEffect(() => { void load() }, [load])
 async function mutate(path: string, method: string, body?: unknown) { setBusy(true); setError(''); setNotice(''); try { await adminFetch(path, { method, body: body ? JSON.stringify(body) : undefined }); setNotice('已保存，权限在下次请求时生效'); await load() } catch (e) { setError(e instanceof Error ? e.message : '保存失败') } finally { setBusy(false) } }
 return <div className="pa-stack"><ErrorBanner message={error} onClose={() => setError('')} />{notice && <p role="status">{notice}</p>}
 <section className="pa-card"><h2>角色与渠道范围</h2><p>内置角色可复制。渠道留空代表全部渠道；有限渠道账号仅能访问支持渠道过滤的功能。动态角色不会授予超级管理员身份。</p>
 <div className="pa-table-wrap"><table className="pa-table"><thead><tr><th>角色</th><th>权限</th><th>渠道</th><th>操作</th></tr></thead><tbody>{roles.map(role => <tr key={role.id}><td>{role.name}{role.builtin ? '（内置）' : ''}</td><td>{role.permissions.join(', ')}</td><td>{role.channels.join(', ') || '全部'}</td><td>{writable && role.key !== 'super_admin' && <><button className="pa-button" onClick={() => setDraft({ ...role, id: role.builtin ? '' : role.id, key: role.builtin ? `${role.key}_custom` : role.key, builtin: false })}>{role.builtin ? '复制' : '编辑'}</button>{!role.builtin && <button className="pa-button" disabled={busy} onClick={() => { if (window.confirm(`删除角色「${role.name}」？`)) void mutate(`/api/admin/roles/${role.id}`, 'DELETE') }}>删除</button>}</>}</td></tr>)}</tbody></table></div></section>
 {writable && <><section className="pa-card"><h2>{draft.id ? '编辑角色' : '创建角色'}</h2><form onSubmit={e => { e.preventDefault(); void mutate('/api/admin/roles', draft.id ? 'PUT' : 'POST', draft) }}><fieldset disabled={busy}><div className="pa-form-grid"><label>标识<input required maxLength={60} disabled={!!draft.id} value={draft.key} onChange={e => setDraft({ ...draft, key: e.target.value })} /></label><label>名称<input required maxLength={100} value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>允许的渠道（逗号分隔）<input value={draft.channels.join(',')} onChange={e => setDraft({ ...draft, channels: e.target.value.split(',').map(v => v.trim()).filter(Boolean) })} /></label></div><div className="pa-form-grid">{permissions.map(permission => <label key={permission}><input type="checkbox" checked={draft.permissions.includes(permission)} onChange={e => setDraft({ ...draft, permissions: e.target.checked ? [...draft.permissions, permission] : draft.permissions.filter(v => v !== permission) })} />{permission}</label>)}</div><button className="pa-button pa-button--primary" type="submit">保存角色</button><button className="pa-button" type="button" onClick={() => setDraft(emptyRole)}>新建</button></fieldset></form></section>
 <section className="pa-card"><h2>分配或撤销后台角色</h2><form className="pa-form-grid" onSubmit={e => { e.preventDefault(); void mutate('/api/admin/roles/assign', 'POST', { user_id: userId, role_id: roleId }) }}><label>账户 ID<input required value={userId} onChange={e => setUserId(e.target.value)} /></label><label>角色<select value={roleId} onChange={e => setRoleId(e.target.value)}><option value="">撤销动态后台权限</option>{roles.filter(role => role.key !== 'super_admin').map(role => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label><button className="pa-button pa-button--primary" disabled={busy}>保存分配</button></form></section></>}
 </div>
}
