import { useEffect, useState } from 'react'
import { adminFetch } from '../../admin/api'
import { ErrorBanner } from './ui'
export function RoutingPage({ writable }: { writable: boolean }) {
 const [amount, setAmount] = useState(2000), [started, setStarted] = useState(''), [route, setRoute] = useState('training'), [userId, setUserId] = useState(''), [userRoute, setUserRoute] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
 useEffect(() => { void adminFetch<{ credit: { starting_usd: number; started_at: string; route: string } }>('/api/admin/routing').then(({ credit }) => { setAmount(credit.starting_usd); setStarted(credit.started_at ? credit.started_at.slice(0, 16) : ''); setRoute(credit.route) }).catch(e => setError(e instanceof Error ? e.message : '读取失败')) }, [])
 async function save(body: unknown) { setBusy(true); setError(''); try { await adminFetch('/api/admin/routing', { method: 'PUT', body: JSON.stringify(body) }); setNotice('已保存，新会话按更新后的路由执行') } catch (e) { setError(e instanceof Error ? e.message : '保存失败') } finally { setBusy(false) } }
 return <div className="pa-stack"><ErrorBanner message={error} onClose={() => setError('')} />{notice && <p role="status">{notice}</p>}<fieldset className="pa-permission-scope" disabled={!writable || busy}><section className="pa-card"><h2>Speechmatics 额度起点</h2><p>填写该上游账户在起算时刻的真实余额。系统扣除此后已记账的上游费用；未记录路由的历史用量无法归入账户。</p><form className="pa-form-grid" onSubmit={e => { e.preventDefault(); void save({ credit_usd: amount, started_at: started ? `${started}:00Z` : '', route }) }}><label>起始余额 USD<input type="number" min="0" max="10000000" step="0.01" value={amount} onChange={e => setAmount(Number(e.target.value))} required /></label><label>起算时间（UTC，留空暂停估算）<input type="datetime-local" value={started} onChange={e => setStarted(e.target.value)} /></label><label>上游账户<select value={route} onChange={e => setRoute(e.target.value)}><option value="training">训练</option><option value="standard">不训练</option></select></label><button className="pa-button pa-button--primary">保存额度配置</button></form></section><section className="pa-card"><h2>指定账户路由</h2><p>机构与赠送余额的保护规则优先于训练账号指定。留空指定可恢复自动选择。</p><form className="pa-form-grid" onSubmit={e => { e.preventDefault(); void save({ user_id: userId, route: userRoute }) }}><label>用户 ID<input required value={userId} onChange={e => setUserId(e.target.value)} /></label><label>路由<select value={userRoute} onChange={e => setUserRoute(e.target.value)}><option value="">自动</option><option value="standard">不训练</option><option value="training">训练</option></select></label><button className="pa-button pa-button--primary">保存账户路由</button></form></section></fieldset></div>
}
